### ISSUE TITLE
Rate limit errors should be logged nicer way

### ISSUE THREAD

**Issue by jancurn** [apify/apify-client-js#130]
Currently, users see this in the log:

```
2019-11-15T10:10:44.402Z WARNING: Retry failed 5 times and will be repeated in 20089ms {"originalError":"API request failed on retry number 6",
 "errorDetails":{"url":"http://172.31.56.216:8010/v2/request-queues/YYY/requests",
"method":"POST",
"qs":{"forefront":false,"token":"*********","clientKey":"XXX"},"hasBody":true,"statusCode":429,"iteration":6}}
```

Which looks a bit scary, for a simple API rate limiting. We should show this error in some nicer way.

**Comment by jancurn** [comment]
Related to https://github.com/apifytech/apify-client-js/issues/137

**Comment by mnmkng** [comment]
With v1 it's much better:

```
WARN  ApifyClient: API request failed 4 times. Max attempts: 9.
Cause:ApifyApiError: You have exceeded the rate limit of 30 requests per second
  clientMethod: KeyValueStoreClient.getRecord
  statusCode: 429
  type: rate-limit-exceeded
  attempt: 4
  httpMethod: get
  path: /v2/key-value-stores/mnmkng~test-123/records/X
  stack: 
    at makeRequest (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/apify/node_modules/apify-client/src/http_client.js:136:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async KeyValueStoreClient.getRecord (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/apify/node_modules/apify-client/src/resource_clients/key_value_store.js:109:30)
```
