### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by jancurn** [apify/apify-client-js#137]
For example, the rate limit excess error is displayed like this, which doesn't tell the user anything. We should show the message from API server at least, and show full query string instead of `qs=[object Object]`

```
2020-02-08T20:00:08.348Z ERROR: The function passed to Apify.main() threw an exception: (error details: type=request-failed, url=http://172.31.57.222:8010/v2/request-queues/XYZ/requests/XYZ, method=GET, qs=[object Object], hasBody=false, error=undefined, statusCode=429, iteration=9)
2020-02-08T20:00:08.350Z   ApifyClientError: API request failed on retry number 9
2020-02-08T20:00:08.351Z     at makeRequest (/usr/src/app/node_modules/apify-client/build/utils.js:187:31)
2020-02-08T20:00:08.352Z     at runMicrotasks (<anonymous>)
2020-02-08T20:00:08.353Z     at processTicksAndRejections (internal/process/task_queues.js:94:5)
2020-02-08T20:00:08.354Z     at async exports.retryWithExpBackoff (/usr/src/app/node_modules/apify-shared/exponential_backoff.js:44:20)
2020-02-08T20:00:08.355Z     at async RequestQueue.getRequest (/usr/src/app/node_modules/apify/build/request_queue.js:331:17)
2020-02-08T20:00:08.356Z     at async RequestQueue.fetchNextRequest (/usr/src/app/node_modules/apify/build/request_queue.js:376:17)
2020-02-08T20:00:08.358Z     at async Promise.all (index 0)
2020-02-08T20:00:08.359Z     at async BasicCrawler._runTaskFunction (/usr/src/app/node_modules/apify/build/crawlers/basic_crawler.js:385:28)
2020-02-08T20:00:08.366Z     at async AutoscaledPool._maybeRunTask (/usr/src/app/node_modules/apify/build/autoscaling/autoscaled_pool.js:463:7)
2020-02-08T20:00:08.591Z npm ERR! code ELIFECYCLE
2020-02-08T20:00:08.592Z npm ERR! errno 91
2020-02-08T20:00:08.594Z npm ERR! apify-tabelog-actor@0.1.0 start: `node src/main.js`
2020-02-08T20:00:08.597Z npm ERR! Exit status 91
2020-02-08T20:00:08.598Z npm ERR! 
2020-02-08T20:00:08.599Z npm ERR! Failed at the apify-tabelog-actor@0.1.0 start script.
2020-02-08T20:00:08.600Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-02-08T20:00:08.601Z 
2020-02-08T20:00:08.603Z npm ERR! A complete log of this run can be found in:
2020-02-08T20:00:08.604Z npm ERR!     /root/.npm/_logs/2020-02-08T20_00_08_591Z-debug.log
```

**Comment by mnmkng** [comment]
With v1 it's much better.

```
WARN  ApifyClient: API request failed 4 times. Max attempts: 9.
Cause:ApifyApiError: You have exceeded the rate limit of 30 requests per second
  clientMethod: KeyValueStoreClient.getRecord
  statusCode: 429
  type: rate-limit-exceeded
  attempt: 4
  httpMethod: get
  path: /v2/key-value-stores/mnmkng~test-123/records/X
  stack: 
    at makeRequest (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/apify/node_modules/apify-client/src/http_client.js:136:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async KeyValueStoreClient.getRecord (/Users/mnmkng/Projects/Apify/Actors/bug-test/node_modules/apify/node_modules/apify-client/src/resource_clients/key_value_store.js:109:30)
```
