### ISSUE TITLE
keyValueStore.getRecord error type does not match error returned from API

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-client-js#148]
If a user tries to access the record in keyValueStore with the invalid token.
The error was thrown:
```
ApifyClientError: Server request failed.
    at exports.newApifyClientErrorFromResponse (/Users/jakubdrobnik/WebstormProjects/apify-work-utils/kvs-test/input-test/node_modules/apify-client/build/utils.js:86:12)
    at makeRequest (/Users/jakubdrobnik/WebstormProjects/apify-work-utils/kvs-test/input-test/node_modules/apify-client/build/utils.js:165:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.retryWithExpBackoff (/Users/jakubdrobnik/WebstormProjects/apify-work-utils/kvs-test/input-test/node_modules/apify-client/node_modules/apify-shared/exponential_backoff.js:44:20)
    at async /Users/jakubdrobnik/WebstormProjects/apify-work-utils/kvs-test/input-test/main.js:16:18
    at async run (/Users/jakubdrobnik/WebstormProjects/apify-work-utils/kvs-test/input-test/node_modules/apify/build/actor.js:195:13) {
  name: 'ApifyClientError',
  type: 'request-failed',
  details: {
    statusCode: 400,
    url: 'https://api.apify.com/v2/key-value-stores/rLJm4L4Skspsl2oaa/records/INPUT',
    method: 'GET'
  }
}
```

The error type doesn't match type of error returned from API:
```
{
    "error": {
        "type": "token-not-found",
        "message": "Authentication token is not valid"
    }
}
```

**Comment by mnmkng** [comment]
Without token it produces:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/23726914/101343568-771a8f80-3884-11eb-9963-2244504340ee.png">

With invalid token it produces:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/23726914/101343597-86014200-3884-11eb-90d3-ab57c83eb019.png">


Client v1 returns `undefined` for the first case (because it's a `404` `record-not-found` and for invalid token it returns this:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/23726914/101343756-c2cd3900-3884-11eb-9a44-ef775fd080c7.png">

So I guess I can close it?
