### ISSUE TITLE
Improve stack traces of errors

### ISSUE THREAD

**Issue by jancurn** [apify/apify-client-js#99]
The stack traces currently don't help with the debugging, because the package doesn't use await/async but Promise chains. For example, the error below doesn't say where in code the problem occurred. I think we can safely move to await/async, or at least have two builds - one for browsers and one for Node.js.

```
2019-02-15T15:46:18.433Z ERROR: PhantomCrawler: Unhandled exception (error details: type=invalid-value, statusCode=400)
2019-02-15T15:46:18.435Z   ApifyClientError: Invalid value provided: id is not allowed by the schema
2019-02-15T15:46:18.437Z     at exports.newApifyClientErrorFromResponse (/home/myuser/node_modules/apify-client/build/utils.js:87:12)
2019-02-15T15:46:18.439Z     at exports.requestPromise (/home/myuser/node_modules/apify-client/build/utils.js:158:19)
2019-02-15T15:46:18.440Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mnmkng** [comment]
Fixed in v1
